language: php

php:
  - 7.0
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction --dev
  - touch ./database/database.sqlite
  - php artisan migrate

env:
  global:
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=base64:ziCTYC4bo+YlRgiuO3Wtg8ap3B/dmn14f55IQvO3W3M=
    - DB_CONNECTION=sqlite
    - CODECLIMATE_REPO_TOKEN=89ac3c612f0b87ed76ebac6e5f9fd25aae74b440a5ba371880211e67c5d153d8
    - cipher=AES-256-CBC
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/test-reporter